### ISSUE TITLE
Doesn't work on Google.com

### ISSUE THREAD

**Issue by jonathan-s** [serverdensity/Fluffify#14]
Trying out the plugin locally works on google. But once uploaded to the Chrome store it doesn't work.

**Comment by frdmn** [comment]
Works for me:

![bildschirmfoto 2015-02-19 um 15 21 36](https://cloud.githubusercontent.com/assets/944459/6268178/1dd7aa1c-b84b-11e4-9be3-3da779c1da70.png)

(German version of google, though)

**Comment by jonathan-s** [comment]
Alright then :)
